
export const colors = {
    normal: '#9099a0',
    bug: '#8FC12C',
    electric:'#F3D13B',
    fighting: '#CD4069',
    ghost: '#5268AB',
    psychic: '#F87176',
    flying: '#92A9DE',
    steel: '#5A8EA1',
    ice: '#74CEBF',
    poison: '#AB6AC8',
    fire: '#FE9C54',
    dragon: '#0A6CC4',
    ground: '#D97745',
    water: '#4C8FD5',
    dark: '#5A5266',
    rock: '#C6B78A',
    grass: '#63BB5A',
    fairy: '#EB8EE5',
}
export const typesPt = {
    normal: 'normal',
    bug: 'inseto',
    electric:'elétrico',
    fighting: 'lutador',
    ghost: 'fantasma',
    psychic: 'psíquico',
    flying: 'voador',
    steel: 'metal',
    ice: 'gelo',
    poison: 'venenoso',
    fire: 'fogo',
    dragon: 'dragão',
    ground: 'terra',
    water: 'água',
    dark: 'noturno',
    rock: 'pedra',
    grass: 'planta',
    fairy: 'fada',
}
